In [21]:
import datetime
from dataclasses import dataclass, field, asdict
import json
from zoneinfo import ZoneInfo
from pathlib import Path
from uuid import uuid4, UUID
from typing import Literal

import polars as pl
from loguru import logger

pl.Config(set_tbl_rows=-1, set_tbl_cols=-1)

In [22]:
@dataclass
class DataTracking:
    id: UUID
    column: str
    old_value: any
    new_value: any
    change_type: Literal["create", "update", "delete"]
    origin_source: Path
    new_source: Path
    created_at: datetime.datetime = field(default_factory=datetime.datetime.now)
    updated_at: datetime.datetime | None = None

In [23]:
def read_checkpoint(file_path: str = "checkpoint/checkpoint.json") -> dict | None:
    """Read checkpoint data."""

    with open(file_path, "r") as f:
        try:
            checkpoint = json.load(f)
            return checkpoint if checkpoint else {}

        except json.decoder.JSONDecodeError as e:
            logger.error(e)
            return None

In [24]:
checkpoint = read_checkpoint("/home/user/workspace3/checkpoint/checkpoint.json")

In [25]:
# Load origin data to raw and capture history
brozend_file_path: Path = Path("/home/user/workspace3/data/brozen/data.parquet")

In [26]:
# Get last load data time
last_load_data_time = datetime.datetime.strptime(checkpoint["load_data"]["end_at"], "%Y-%m-%d %H:%M:%S").replace(tzinfo=ZoneInfo("Asia/Ho_Chi_Minh"))
last_load_data_time

datetime.datetime(2026, 7, 28, 18, 9, 18, tzinfo=zoneinfo.ZoneInfo(key='Asia/Ho_Chi_Minh'))

In [27]:
# Load new data from staging
new_source_path = "/home/user/workspace3/data/staging/v2/data.parquet"
df_new = pl.scan_parquet(new_source_path)
df_new.first().collect()

shape: (1, 8)
┌───────┬──────────────┬─────────────┬─────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ index ┆ id           ┆ name        ┆ age ┆ gender      ┆ address     ┆ created_at  ┆ updated_at  │
│ ---   ┆ ---          ┆ ---         ┆ --- ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ u32   ┆ str          ┆ str         ┆ i64 ┆ str         ┆ str         ┆ datetime[μs ┆ datetime[μs │
│       ┆              ┆             ┆     ┆             ┆             ┆ , Asia/Ho_C ┆ , Asia/Ho_C │
│       ┆              ┆             ┆     ┆             ┆             ┆ hi_Minh]    ┆ hi_Minh]    │
╞═══════╪══════════════╪═════════════╪═════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 1     ┆ 44a6bafe-fa8 ┆ user_1_chan ┆ 21  ┆ male_change ┆ address_0_c ┆ 2026-07-26  ┆ 2026-07-28  │
│       ┆ 0-4e56-818a- ┆ ge_all      ┆     ┆ _all        ┆ hange_all   ┆ 18:09:17.40 ┆ 18:09:17.40 │
│       ┆ aaf61b…      ┆             ┆     ┆             ┆             ┆ 5005 +07    ┆ 5203 +07    │
└───────┴──────────────┴─────────────┴─────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [28]:
# Load current data in brozen
current_data_path = "/home/user/workspace3/data/brozen/data.parquet"
df_current = pl.scan_parquet(current_data_path)
df_current.first().collect()

shape: (1, 8)
┌───────┬──────────────────┬────────┬─────┬────────┬───────────┬─────────────────┬─────────────────┐
│ index ┆ id               ┆ name   ┆ age ┆ gender ┆ address   ┆ created_at      ┆ updated_at      │
│ ---   ┆ ---              ┆ ---    ┆ --- ┆ ---    ┆ ---       ┆ ---             ┆ ---             │
│ u32   ┆ str              ┆ str    ┆ i64 ┆ str    ┆ str       ┆ datetime[μs,    ┆ datetime[μs,    │
│       ┆                  ┆        ┆     ┆        ┆           ┆ Asia/Ho_Chi_Min ┆ Asia/Ho_Chi_Min │
│       ┆                  ┆        ┆     ┆        ┆           ┆ h]              ┆ h]              │
╞═══════╪══════════════════╪════════╪═════╪════════╪═══════════╪═════════════════╪═════════════════╡
│ 1     ┆ 44a6bafe-fa80-4e ┆ user_1 ┆ 20  ┆ male   ┆ address_0 ┆ 2026-07-27      ┆ 2026-07-27      │
│       ┆ 56-818a-aaf61b…  ┆        ┆     ┆        ┆           ┆ 18:09:17.405005 ┆ 18:09:17.405203 │
│       ┆                  ┆        ┆     ┆        ┆           ┆ +07             ┆ +07             │
└───────┴──────────────────┴────────┴─────┴────────┴───────────┴─────────────────┴─────────────────┘

In [29]:
# Hash row data
import hashlib

def hash_row_data(data) -> str:
    row_str = "|".join(str(value) for value in data)
    return hashlib.sha256(row_str.encode("utf-8")).hexdigest()

# Example:
row_data_current = hash_row_data(df_current.first().collect())
row_data_new = hash_row_data(df_new.first().collect())

print(row_data_current)
print(row_data_new)
print(row_data_current == row_data_new)

67cac7de684e40111d9a5ef286e7d70f0d55d35c8655d013a1cb653f107f16bc
5e9ee8d7be91eced564d8d4bfceef6218ae09bd934ca881b7e970e4742e39b51
False

In [30]:
import hashlib
import polars as pl

def batch_sha256(s: pl.Series) -> pl.Series:
    """Hashes a Polars Series in bulk using Python's hashlib."""
    return pl.Series(
        [hashlib.sha256(val.encode("utf-8")).hexdigest() for val in s]
    )

df_current_hashed = (
    df_current.with_columns(
        pl.all().cast(pl.String).fill_null("")
    )
    .with_columns(
        pl.concat_str(pl.all(), separator="|")
        .map_batches(batch_sha256)
        .alias("hashed_row")
    )
)

df_current_hashed.first().collect()

shape: (1, 9)
┌───────┬─────────────┬────────┬─────┬────────┬───────────┬─────────────┬─────────────┬────────────┐
│ index ┆ id          ┆ name   ┆ age ┆ gender ┆ address   ┆ created_at  ┆ updated_at  ┆ hashed_row │
│ ---   ┆ ---         ┆ ---    ┆ --- ┆ ---    ┆ ---       ┆ ---         ┆ ---         ┆ ---        │
│ str   ┆ str         ┆ str    ┆ str ┆ str    ┆ str       ┆ str         ┆ str         ┆ str        │
╞═══════╪═════════════╪════════╪═════╪════════╪═══════════╪═════════════╪═════════════╪════════════╡
│ 1     ┆ 44a6bafe-fa ┆ user_1 ┆ 20  ┆ male   ┆ address_0 ┆ 2026-07-27  ┆ 2026-07-27  ┆ 992e810853 │
│       ┆ 80-4e56-818 ┆        ┆     ┆        ┆           ┆ 18:09:17.40 ┆ 18:09:17.40 ┆ ddfc80eac6 │
│       ┆ a-aaf61b…   ┆        ┆     ┆        ┆           ┆ 5005+07:…   ┆ 5203+07:…   ┆ 9eec8f3f0c │
│       ┆             ┆        ┆     ┆        ┆           ┆             ┆             ┆ …          │
└───────┴─────────────┴────────┴─────┴────────┴───────────┴─────────────┴─────────────┴────────────┘

In [31]:
df_new_hashed = (
    df_new.with_columns(
        pl.all().cast(pl.String).fill_null("")
    )
    .with_columns(
        pl.concat_str(pl.all(), separator="|")
        .map_batches(batch_sha256)
        .alias("hashed_row")
    )
)

df_new_hashed.first().collect()

shape: (1, 9)
┌───────┬────────────┬───────────┬─────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ index ┆ id         ┆ name      ┆ age ┆ gender    ┆ address   ┆ created_a ┆ updated_a ┆ hashed_ro │
│ ---   ┆ ---        ┆ ---       ┆ --- ┆ ---       ┆ ---       ┆ t         ┆ t         ┆ w         │
│ str   ┆ str        ┆ str       ┆ str ┆ str       ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│       ┆            ┆           ┆     ┆           ┆           ┆ str       ┆ str       ┆ str       │
╞═══════╪════════════╪═══════════╪═════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1     ┆ 44a6bafe-f ┆ user_1_ch ┆ 21  ┆ male_chan ┆ address_0 ┆ 2026-07-2 ┆ 2026-07-2 ┆ a8c156660 │
│       ┆ a80-4e56-8 ┆ ange_all  ┆     ┆ ge_all    ┆ _change_a ┆ 6 18:09:1 ┆ 8 18:09:1 ┆ 6bd3e1214 │
│       ┆ 18a-aaf61b ┆           ┆     ┆           ┆ ll        ┆ 7.405005+ ┆ 7.405203+ ┆ 242eb3866 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 2e9…      │
└───────┴────────────┴───────────┴─────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [32]:
# Find changed record
# df_changed = df_new_hashed.join(df_current_hashed, how="anti", on="hashed_row")
# df_changed.select(pl.len()).collect().item()

In [33]:
# Find record new
df_data_new = df_new_hashed.filter(
    ~pl.col("id").is_in(
        df_current_hashed.select("id")
        .collect()
        .to_series()
        .implode()
    )
)
logger.info(f"Data new: {df_data_new.select(pl.len()).collect().item()}")

2026-07-28 11:09:20.564 | INFO     | __main__:<module>:10 - Data new: 10

In [34]:
# Find record deleted
df_data_deleted = df_current_hashed.filter(
    ~pl.col("id").is_in(
        df_new_hashed.select("id")
        .collect()
        .to_series()
        .implode()
    ))
logger.info(f"Data deleted: {df_data_deleted.select(pl.len()).collect().item()}")

2026-07-28 11:09:20.641 | INFO     | __main__:<module>:9 - Data deleted: 10

In [35]:
# Find record not change
df_data_not_change = df_current_hashed.filter(
    pl.col("hashed_row").is_in(
        df_new_hashed.select("hashed_row")
        .collect()
        .to_series()
        .implode()
    )
)
logger.info(f"Data not change: {df_data_not_change.select(pl.len()).collect().item()}")

2026-07-28 11:09:20.709 | INFO     | __main__:<module>:10 - Data not change: 20

In [36]:
# Find data change
exclude_ids = df_data_new.select("id").collect().to_series().to_list() + df_data_not_change.select("id").collect().to_series().to_list()
len(exclude_ids)

df_new_hashed_change = df_new_hashed.filter(
    ~pl.col("id").is_in(exclude_ids)
)
df_new_hashed_change.select(pl.len()).collect().item()

70

In [37]:
exclude_ids = df_data_deleted.select("id").collect().to_series().to_list() + df_data_not_change.select("id").collect().to_series().to_list()
len(exclude_ids)
df_current_hashed_change = df_current_hashed.filter(
    ~pl.col("id").is_in(exclude_ids)
)
df_current_hashed_change.select(pl.len()).collect().item()

70

In [38]:
business_cols = [str(key) for key in df_current.collect_schema() if key not in ("id", "index")]
business_cols

['name', 'age', 'gender', 'address', 'created_at', 'updated_at']

In [39]:
# if df_new_hashed_change.select(pl.len()).collect().item() > 0:
change_log = []
for col in business_cols:
    merged = (
                df_current_hashed_change.select(["id", col]).rename({col: "old_value"})
                .join(df_new_hashed_change.select(["id", col]).rename({col: "new_value"}), on="id")
                .filter(pl.col("old_value") != pl.col("new_value"))
                .collect()
            )
    if len(merged) > 0:
        change_log.append(merged.with_columns(pl.lit(col).alias("column")))
change_log

[shape: (20, 4)
 ┌─────────────────────────────────┬───────────┬─────────────────────┬────────┐
 │ id                              ┆ old_value ┆ new_value           ┆ column │
 │ ---                             ┆ ---       ┆ ---                 ┆ ---    │
 │ str                             ┆ str       ┆ str                 ┆ str    │
 ╞═════════════════════════════════╪═══════════╪═════════════════════╪════════╡
 │ 44a6bafe-fa80-4e56-818a-aaf61b… ┆ user_1    ┆ user_1_change_all   ┆ name   │
 │ 9f5b1f54-1be6-41a4-99a2-470b17… ┆ user_2    ┆ user_2_change_all   ┆ name   │
 │ 00c62c9d-1d87-4f07-b6a1-e5ca64… ┆ user_3    ┆ user_3_change_all   ┆ name   │
 │ eba44ee1-49ca-476b-bd90-cd4262… ┆ user_4    ┆ user_4_change_all   ┆ name   │
 │ a8db67f8-862b-44a6-a643-f1220b… ┆ user_5    ┆ user_5_change_all   ┆ name   │
 │ b2233fde-1004-4465-b302-f1a22a… ┆ user_6    ┆ user_6_change_all   ┆ name   │
 │ 6ad50c96-3690-47bb-ad54-ccd32e… ┆ user_7    ┆ user_7_change_all   ┆ name   │
 │ 1f64b83d-2e73-4438-b3ee-fa843b… ┆ user_8    ┆ user_8_change_all   ┆ name   │
 │ 402b24cf-7090-44ec-ac64-eadb63… ┆ user_9    ┆ user_9_change_all   ┆ name   │
 │ 8af206ac-7416-40cc-a063-2252a2… ┆ user_10   ┆ user_10_change_all  ┆ name   │
 │ 502bba29-e68c-4011-9b05-fcf9fc… ┆ user_11   ┆ user_11_change_name ┆ name   │
 │ e5c60e19-bf4c-4286-adf9-4fef28… ┆ user_12   ┆ user_12_change_name ┆ name   │
 │ e04c96e6-b26b-454e-9f4e-948196… ┆ user_13   ┆ user_13_change_name ┆ name   │
 │ eac32e99-28a7-4502-87a5-469976… ┆ user_14   ┆ user_14_change_name ┆ name   │
 │ 0850cba8-8237-49bc-bddd-87239a… ┆ user_15   ┆ user_15_change_name ┆ name   │
 │ c7e8d8dc-4f55-42f8-86ec-4c07d0… ┆ user_16   ┆ user_16_change_name ┆ name   │
 │ c9fd6492-9012-4545-ac46-d36e70… ┆ user_17   ┆ user_17_change_name ┆ name   │
 │ b2b03413-fa42-4740-8ace-86806d… ┆ user_18   ┆ user_18_change_name ┆ name   │
 │ de963735-469e-41e2-857b-da3537… ┆ user_19   ┆ user_19_change_name ┆ name   │
 │ 94038139-6b0b-4de9-a0fe-ea9d95… ┆ user_20   ┆ user_20_change_name ┆ name   │
 └─────────────────────────────────┴───────────┴─────────────────────┴────────┘,
 shape: (20, 4)
 ┌─────────────────────────────────┬───────────┬───────────┬────────┐
 │ id                              ┆ old_value ┆ new_value ┆ column │
 │ ---                             ┆ ---       ┆ ---       ┆ ---    │
 │ str                             ┆ str       ┆ str       ┆ str    │
 ╞═════════════════════════════════╪═══════════╪═══════════╪════════╡
 │ 44a6bafe-fa80-4e56-818a-aaf61b… ┆ 20        ┆ 21        ┆ age    │
 │ 9f5b1f54-1be6-41a4-99a2-470b17… ┆ 62        ┆ 63        ┆ age    │
 │ 00c62c9d-1d87-4f07-b6a1-e5ca64… ┆ 64        ┆ 65        ┆ age    │
 │ eba44ee1-49ca-476b-bd90-cd4262… ┆ 23        ┆ 24        ┆ age    │
 │ a8db67f8-862b-44a6-a643-f1220b… ┆ 27        ┆ 28        ┆ age    │
 │ b2233fde-1004-4465-b302-f1a22a… ┆ 38        ┆ 39        ┆ age    │
 │ 6ad50c96-3690-47bb-ad54-ccd32e… ┆ 21        ┆ 22        ┆ age    │
 │ 1f64b83d-2e73-4438-b3ee-fa843b… ┆ 27        ┆ 28        ┆ age    │
 │ 402b24cf-7090-44ec-ac64-eadb63… ┆ 40        ┆ 41        ┆ age    │
 │ 8af206ac-7416-40cc-a063-2252a2… ┆ 29        ┆ 30        ┆ age    │
 │ cdab23d8-aad5-4979-a03c-5e239d… ┆ 56        ┆ 58        ┆ age    │
 │ 50f05113-18f5-4da7-b76e-742c1d… ┆ 48        ┆ 50        ┆ age    │
 │ 2644eba8-f53b-4ccd-aef0-03b069… ┆ 56        ┆ 58        ┆ age    │
 │ 2782a94e-116a-4da3-84a6-0808e5… ┆ 61        ┆ 63        ┆ age    │
 │ 2db8dd48-d758-406f-aba2-05679a… ┆ 44        ┆ 46        ┆ age    │
 │ 43a6e2e7-109d-4158-9e34-11cd46… ┆ 28        ┆ 30        ┆ age    │
 │ f0ae2ee9-f9a1-4673-86dc-b6329d… ┆ 51        ┆ 53        ┆ age    │
 │ a2b4d573-697d-40ff-84ee-334a91… ┆ 55        ┆ 57        ┆ age    │
 │ 24e8944a-84f7-433c-9041-db36f6… ┆ 52        ┆ 54        ┆ age    │
 │ 658530c0-aa29-44bd-96eb-bdbc29… ┆ 22        ┆ 24        ┆ age    │
 └─────────────────────────────────┴───────────┴───────────┴────────┘,
 shape: (20, 4)
 ┌─────────────────────────────────┬───────────┬──────────────────────┬────────┐
 │ id                              ┆ old_value ┆ new_value            ┆ column │
 │ ---                             ┆ ---       ┆ ---                  ┆ ---    │
 │ str                             ┆ str       ┆ str                  ┆ str    │
 ╞═════════════════════════════════╪═══════════╪══════════════════════╪════════╡
 │ 44a6bafe-fa80-4e56-818a-aaf61b… ┆ male      ┆ male_change_all      ┆ gender │
 │ 9f5b1f54-1be6-41a4-99a2-470b17… ┆ other     ┆ other_change_all     ┆ gender │
 │ 00c62c9d-1d87-4f07-b6a1-e5ca64… ┆ male      ┆ male_change_all      ┆ gender │
 │ eba44ee1-49ca-476b-bd90-cd4262… ┆ male      ┆ male_change_all      ┆ gender │
 │ a8db67f8-862b-44a6-a643-f1220b… ┆ female    ┆ female_change_all    ┆ gender │
 │ b2233fde-1004-4465-b302-f1a22a… ┆ other     ┆ other_change_all     ┆ gender │
 │ 6ad50c96-3690-47bb-ad54-ccd32e… ┆ male      ┆ male_change_all      ┆ gender │
 │ 1f64b83d-2e73-4438-b3ee-fa843b… ┆ other     ┆ other_change_all     ┆ gender │
 │ 402b24cf-7090-44ec-ac64-eadb63… ┆ other     ┆ other_change_all     ┆ gender │
 │ 8af206ac-7416-40cc-a063-2252a2… ┆ male      ┆ male_change_all      ┆ gender │
 │ e600652c-5049-4bcd-8747-21c8f4… ┆ male      ┆ male_change_gender   ┆ gender │
 │ 34755271-37f5-47bd-be58-32382a… ┆ male      ┆ male_change_gender   ┆ gender │
 │ f162325a-d398-4c7b-9e6b-f7da45… ┆ other     ┆ other_change_gender  ┆ gender │
 │ 34d4c530-0394-4834-bef5-175b04… ┆ other     ┆ other_change_gender  ┆ gender │
 │ e93ec9bb-741a-4745-af55-9e3e79… ┆ female    ┆ female_change_gender ┆ gender │
 │ 05c4d0f4-9cc7-4502-bd59-04fcb6… ┆ female    ┆ female_change_gender ┆ gender │
 │ 2464bad5-173e-454c-8236-80fed3… ┆ male      ┆ male_change_gender   ┆ gender │
 │ 9ac1283c-ef51-4b49-9118-bd7184… ┆ male      ┆ male_change_gender   ┆ gender │
 │ 7cffbdde-5a3d-425f-8f5f-0b0b60… ┆ female    ┆ female_change_gender ┆ gender │
 │ d45fd9bf-69c1-403e-9850-06d692… ┆ other     ┆ other_change_gender  ┆ gender │
 └─────────────────────────────────┴───────────┴──────────────────────┴────────┘,
 shape: (20, 4)
 ┌─────────────────────────────────┬────────────┬───────────────────────────┬─────────┐
 │ id                              ┆ old_value  ┆ new_value                 ┆ column  │
 │ ---                             ┆ ---        ┆ ---                       ┆ ---     │
 │ str                             ┆ str        ┆ str                       ┆ str     │
 ╞═════════════════════════════════╪════════════╪═══════════════════════════╪═════════╡
 │ 44a6bafe-fa80-4e56-818a-aaf61b… ┆ address_0  ┆ address_0_change_all      ┆ address │
 │ 9f5b1f54-1be6-41a4-99a2-470b17… ┆ address_1  ┆ address_1_change_all      ┆ address │
 │ 00c62c9d-1d87-4f07-b6a1-e5ca64… ┆ address_2  ┆ address_2_change_all      ┆ address │
 │ eba44ee1-49ca-476b-bd90-cd4262… ┆ address_3  ┆ address_3_change_all      ┆ address │
 │ a8db67f8-862b-44a6-a643-f1220b… ┆ address_4  ┆ address_4_change_all      ┆ address │
 │ b2233fde-1004-4465-b302-f1a22a… ┆ address_5  ┆ address_5_change_all      ┆ address │
 │ 6ad50c96-3690-47bb-ad54-ccd32e… ┆ address_6  ┆ address_6_change_all      ┆ address │
 │ 1f64b83d-2e73-4438-b3ee-fa843b… ┆ address_7  ┆ address_7_change_all      ┆ address │
 │ 402b24cf-7090-44ec-ac64-eadb63… ┆ address_8  ┆ address_8_change_all      ┆ address │
 │ 8af206ac-7416-40cc-a063-2252a2… ┆ address_9  ┆ address_9_change_all      ┆ address │
 │ f1bc2c1c-437d-40f2-b847-af3a15… ┆ address_40 ┆ address_40_change_address ┆ address │
 │ 9780e6b0-9083-470a-83dd-ebb47c… ┆ address_41 ┆ address_41_change_address ┆ address │
 │ 9eb494c4-b1a1-4c2b-8244-4274c9… ┆ address_42 ┆ address_42_change_address ┆ address │
 │ d8bde7fd-7c23-42d4-8717-d267f5… ┆ address_43 ┆ address_43_change_address ┆ address │
 │ cd57bd60-4386-448c-bfff-c8976d… ┆ address_44 ┆ address_44_change_address ┆ address │
 │ 379a6312-d65e-4e31-8d88-26993b… ┆ address_45 ┆ address_45_change_address ┆ address │
 │ 9477ff6f-fdb7-443d-b976-4ee870… ┆ address_46 ┆ address_46_change_address ┆ address │
 │ 806057e2-c5f5-47d4-832f-4dfbb8… ┆ address_47 ┆ address_47_change_address ┆ address │
 │ 25e12fc6-f31f-4657-9787-4928db… ┆ address_48 ┆ address_48_change_address ┆ address │
 │ c89bd116-0c52-4007-b352-4e7001… ┆ address_49 ┆ address_49_change_address ┆ address │
 └─────────────────────────────────┴────────────┴───────────────────────────┴─────────┘,
 shape: (20, 4)
 ┌───────────────────────────────────┬────────────────────────┬────────────────────────┬────────────┐
 │ id                                ┆ old_value              ┆ new_value              ┆ column     │
 │ ---                               ┆ ---                    ┆ ---                    ┆ ---        │
 │ str                               ┆ str                    ┆ str                    ┆ str        │
 ╞═══════════════════════════════════╪════════════════════════╪════════════════════════╪════════════╡
 │ 44a6bafe-fa80-4e56-818a-aaf61b…   ┆ 2026-07-27             ┆ 2026-07-26             ┆ created_at │
 │                                   ┆ 18:09:17.405005+07:…   ┆ 18:09:17.405005+07:…   ┆            │
 │ 9f5b1f54-1be6-41a4-99a2-470b17…   ┆ 2026-07-27             ┆ 2026-07-26             ┆ created_at │
 │                                   ┆ 18:09:17.405024+07:…   ┆ 18:09:17.405024+07:…   ┆            │
 │ 00c62c9d-1d87-4f07-b6a1-e5ca64…   ┆ 2026-07-27             ┆ 2026-07-26             ┆ created_at │
 │                                   ┆ 18:09:17.405026+07:…   ┆ 18:09:17.405026+07:…   ┆            │
 │ eba44ee1-49ca-476b-bd90-cd4262…   ┆ 2026-07-27             ┆ 2026-07-26             ┆ created_at │
 │                                   ┆ 18:09:17.405027+07:…   ┆ 18:09:17.405027+07:…   ┆            │
 │ a8db67f8-862b-44a6-a643-f1220b…   ┆ 2026-07-27             ┆ 2026-07-26             ┆ created_at │
 │                                   ┆ 18:09:17.405029+07:…   ┆ 18:09:17.405029+07:…   ┆            │
 │ b2233fde-1004-4465-b302-f1a22a…   ┆ 2026-07-27             ┆ 2026-07-26             ┆ created_at │
 │                                   ┆ 18:09:17.405031+07:…   ┆ 18:09:17.405031+07:…   ┆            │
 │ 6ad50c96-3690-47bb-ad54-ccd32e…   ┆ 2026-07-27             ┆ 2026-07-26             ┆ created_at │
 │                                   ┆ 18:09:17.405032+07:…   ┆ 18:09:17.405032+07:…   ┆            │
 │ 1f64b83d-2e73-4438-b3ee-fa843b…   ┆ 2026-07-27             ┆ 2026-07-26             ┆ created_at │
 │                                   ┆ 18:09:17.405036+07:…   ┆ 18:09:17.405036+07:…   ┆            │
 │ 402b24cf-7090-44ec-ac64-eadb63…   ┆ 2026-07-27             ┆ 2026-07-26             ┆ created_at │
 │                                   ┆ 18:09:17.405038+07:…   ┆ 18:09:17.405038+07:…   ┆            │
 │ 8af206ac-7416-40cc-a063-2252a2…   ┆ 2026-07-27             ┆ 2026-07-26             ┆ created_at │
 │                                   ┆ 18:09:17.405040+07:…   ┆ 18:09:17.405040+07:…   ┆            │
 │ 53281e28-e69a-44ed-ad4a-44dce8…   ┆ 2026-07-27             ┆ 2026-07-25             ┆ created_at │
 │                                   ┆ 18:09:17.405107+07:…   ┆ 18:09:17.405107+07:…   ┆            │
 │ 2a51e1d6-a7a5-4d82-a65e-1296af…   ┆ 2026-07-27             ┆ 2026-07-25             ┆ created_at │
 │                                   ┆ 18:09:17.405109+07:…   ┆ 18:09:17.405109+07:…   ┆            │
 │ cd4910e1-ca4b-4513-9cb9-1e9dd8…   ┆ 2026-07-27             ┆ 2026-07-25             ┆ created_at │
 │                                   ┆ 18:09:17.405110+07:…   ┆ 18:09:17.405110+07:…   ┆            │
 │ 5f267818-ccf5-4abf-8d3f-08e2ac…   ┆ 2026-07-27             ┆ 2026-07-25             ┆ created_at │
 │                                   ┆ 18:09:17.405112+07:…   ┆ 18:09:17.405112+07:…   ┆            │
 │ ddccd9b3-ebc8-4957-8344-39c666…   ┆ 2026-07-27             ┆ 2026-07-25             ┆ created_at │
 │                                   ┆ 18:09:17.405114+07:…   ┆ 18:09:17.405114+07:…   ┆            │
 │ f45b477c-992d-4f05-b21c-56b8fc…   ┆ 2026-07-27             ┆ 2026-07-25             ┆ created_at │
 │                                   ┆ 18:09:17.405115+07:…   ┆ 18:09:17.405115+07:…   ┆            │
 │ 8fb81afb-19a1-4b6a-a7c3-314ad6…   ┆ 2026-07-27             ┆ 2026-07-25             ┆ created_at │
 │                                   ┆ 18:09:17.405117+07:…   ┆ 18:09:17.405117+07:…   ┆            │
 │ cb49f253-cdb9-492a-8208-be9736…   ┆ 2026-07-27             ┆ 2026-07-25             ┆ created_at │
 │                                   ┆ 18:09:17.405118+07:…   ┆ 18:09:17.405118+07:…   ┆            │
 │ 4cd975b9-0b03-4197-bdb8-90b4f1…   ┆ 2026-07-27             ┆ 2026-07-25             ┆ created_at │
 │                                   ┆ 18:09:17.405136+07:…   ┆ 18:09:17.405136+07:…   ┆            │
 │ 8b16f490-9b2d-4664-8882-5de5a9…   ┆ 2026-07-27             ┆ 2026-07-25             ┆ created_at │
 │                                   ┆ 18:09:17.405138+07:…   ┆ 18:09:17.405138+07:…   ┆            │
 └───────────────────────────────────┴────────────────────────┴────────────────────────┴────────────┘,
 shape: (20, 4)
 ┌───────────────────────────────────┬────────────────────────┬────────────────────────┬────────────┐
 │ id                                ┆ old_value              ┆ new_value              ┆ column     │
 │ ---                               ┆ ---                    ┆ ---                    ┆ ---        │
 │ str                               ┆ str                    ┆ str                    ┆ str        │
 ╞═══════════════════════════════════╪════════════════════════╪════════════════════════╪════════════╡
 │ 44a6bafe-fa80-4e56-818a-aaf61b…   ┆ 2026-07-27             ┆ 2026-07-28             ┆ updated_at │
 │                                   ┆ 18:09:17.405203+07:…   ┆ 18:09:17.405203+07:…   ┆            │
 │ 9f5b1f54-1be6-41a4-99a2-470b17…   ┆ 2026-07-27             ┆ 2026-07-28             ┆ updated_at │
 │                                   ┆ 18:09:17.405205+07:…   ┆ 18:09:17.405205+07:…   ┆            │
 │ 00c62c9d-1d87-4f07-b6a1-e5ca64…   ┆ 2026-07-27             ┆ 2026-07-28             ┆ updated_at │
 │                                   ┆ 18:09:17.405206+07:…   ┆ 18:09:17.405206+07:…   ┆            │
 │ eba44ee1-49ca-476b-bd90-cd4262…   ┆ 2026-07-27             ┆ 2026-07-28             ┆ updated_at │
 │                                   ┆ 18:09:17.405208+07:…   ┆ 18:09:17.405208+07:…   ┆            │
 │ a8db67f8-862b-44a6-a643-f1220b…   ┆ 2026-07-27             ┆ 2026-07-28             ┆ updated_at │
 │                                   ┆ 18:09:17.405209+07:…   ┆ 18:09:17.405209+07:…   ┆            │
 │ b2233fde-1004-4465-b302-f1a22a…   ┆ 2026-07-27             ┆ 2026-07-28             ┆ updated_at │
 │                                   ┆ 18:09:17.405211+07:…   ┆ 18:09:17.405211+07:…   ┆            │
 │ 6ad50c96-3690-47bb-ad54-ccd32e…   ┆ 2026-07-27             ┆ 2026-07-28             ┆ updated_at │
 │                                   ┆ 18:09:17.405213+07:…   ┆ 18:09:17.405213+07:…   ┆            │
 │ 1f64b83d-2e73-4438-b3ee-fa843b…   ┆ 2026-07-27             ┆ 2026-07-28             ┆ updated_at │
 │                                   ┆ 18:09:17.405215+07:…   ┆ 18:09:17.405215+07:…   ┆            │
 │ 402b24cf-7090-44ec-ac64-eadb63…   ┆ 2026-07-27             ┆ 2026-07-28             ┆ updated_at │
 │                                   ┆ 18:09:17.405216+07:…   ┆ 18:09:17.405216+07:…   ┆            │
 │ 8af206ac-7416-40cc-a063-2252a2…   ┆ 2026-07-27             ┆ 2026-07-28             ┆ updated_at │
 │                                   ┆ 18:09:17.405218+07:…   ┆ 18:09:17.405218+07:…   ┆            │
 │ af04206b-981f-4018-9fc6-e17529…   ┆ 2026-07-27             ┆ 2026-07-29             ┆ updated_at │
 │                                   ┆ 18:09:17.405302+07:…   ┆ 18:09:17.405302+07:…   ┆            │
 │ bac95e3c-f10b-481d-a019-26d3e3…   ┆ 2026-07-27             ┆ 2026-07-29             ┆ updated_at │
 │                                   ┆ 18:09:17.405303+07:…   ┆ 18:09:17.405303+07:…   ┆            │
 │ 35767e7c-1840-4b1c-8cf3-970fd9…   ┆ 2026-07-27             ┆ 2026-07-29             ┆ updated_at │
 │                                   ┆ 18:09:17.405305+07:…   ┆ 18:09:17.405305+07:…   ┆            │
 │ 2c4ebaa9-1d03-4f2b-ad3b-8e8ea8…   ┆ 2026-07-27             ┆ 2026-07-29             ┆ updated_at │
 │                                   ┆ 18:09:17.405306+07:…   ┆ 18:09:17.405306+07:…   ┆            │
 │ abc63544-6db9-4105-978e-f34e30…   ┆ 2026-07-27             ┆ 2026-07-29             ┆ updated_at │
 │                                   ┆ 18:09:17.405307+07:…   ┆ 18:09:17.405307+07:…   ┆            │
 │ 904d0938-b71d-4dac-8145-0a266b…   ┆ 2026-07-27             ┆ 2026-07-29             ┆ updated_at │
 │                                   ┆ 18:09:17.405309+07:…   ┆ 18:09:17.405309+07:…   ┆            │
 │ d457f579-2afc-47ef-99a4-f00626…   ┆ 2026-07-27             ┆ 2026-07-29             ┆ updated_at │
 │                                   ┆ 18:09:17.405311+07:…   ┆ 18:09:17.405311+07:…   ┆            │
 │ 0b4a6b93-183d-4729-9e7e-75ddeb…   ┆ 2026-07-27             ┆ 2026-07-29             ┆ updated_at │
 │                                   ┆ 18:09:17.405312+07:…   ┆ 18:09:17.405312+07:…   ┆            │
 │ 5b6e021e-ebd7-4f7c-a146-f8ae87…   ┆ 2026-07-27             ┆ 2026-07-29             ┆ updated_at │
 │                                   ┆ 18:09:17.405314+07:…   ┆ 18:09:17.405314+07:…   ┆            │
 │ 712541bf-7032-4279-a9dc-d9ef9d…   ┆ 2026-07-27             ┆ 2026-07-29             ┆ updated_at │
 │                                   ┆ 18:09:17.405315+07:…   ┆ 18:09:17.405315+07:…   ┆            │
 └───────────────────────────────────┴────────────────────────┴────────────────────────┴────────────┘]

In [46]:
pl.concat(change_log).with_columns(
    pl.lit(datetime.datetime.now(tz=ZoneInfo("Asia/Ho_Chi_Minh"))).alias("capture_at")
).write_database(
    table_name="changelog",
    connection="sqlite:////home/user/workspace3/changelog/changelog.db",  # Path to SQLite file
    if_table_exists="append",  # 'fail', 'replace', or 'append'
)

120

In [ ]:
# Delete data
df_current_hashed = df_current_hashed.filter(
    ~pl.col("id").is_in(
        df_data_deleted.select("id")
        .collect()
        .to_series()
        .implode()
    ))

df_current_hashed = df_current_hashed.filter(
    ~pl.col("id")
    .is_in(
        df_current_hashed_change.select("id")
        .collect()
        .to_series()
        .implode()
    )
)

In [ ]:
# Add new data
df_current_hashed = pl.concat([df_current_hashed, df_data_new, df_new_hashed_change])

In [ ]:
df_current_hashed.select(pl.len()).collect().item()

100

In [ ]:
df_current_hashed.collect()

shape: (100, 9)
┌───────┬────────────┬───────────┬─────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ index ┆ id         ┆ name      ┆ age ┆ gender    ┆ address   ┆ created_a ┆ updated_a ┆ hashed_ro │
│ ---   ┆ ---        ┆ ---       ┆ --- ┆ ---       ┆ ---       ┆ t         ┆ t         ┆ w         │
│ str   ┆ str        ┆ str       ┆ str ┆ str       ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│       ┆            ┆           ┆     ┆           ┆           ┆ str       ┆ str       ┆ str       │
╞═══════╪════════════╪═══════════╪═════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 72    ┆ 6bafdc33-0 ┆ user_72   ┆ 42  ┆ male      ┆ address_7 ┆ 2026-07-2 ┆ 2026-07-2 ┆ a168b922f │
│       ┆ a08-4f8b-b ┆           ┆     ┆           ┆ 1         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ db4b78277 │
│       ┆ 065-a65836 ┆           ┆     ┆           ┆           ┆ 3.452448+ ┆ 3.452583+ ┆ 834922f51 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 1d3…      │
│ 73    ┆ 8101f717-b ┆ user_73   ┆ 20  ┆ female    ┆ address_7 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 887a3cb25 │
│       ┆ 7d9-4b32-8 ┆           ┆     ┆           ┆ 2         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ 0c84c216f │
│       ┆ 24f-9a2d6e ┆           ┆     ┆           ┆           ┆ 3.452449+ ┆ 3.452584+ ┆ 07e54087b │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 580…      │
│ 74    ┆ 0949b06b-6 ┆ user_74   ┆ 58  ┆ male      ┆ address_7 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 32982d271 │
│       ┆ 3bd-4bfa-b ┆           ┆     ┆           ┆ 3         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ c35ae32e2 │
│       ┆ 42b-0746f7 ┆           ┆     ┆           ┆           ┆ 3.452450+ ┆ 3.452586+ ┆ a4c124fb4 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 7de…      │
│ 75    ┆ 11ae7024-c ┆ user_75   ┆ 24  ┆ other     ┆ address_7 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 8c6c71a11 │
│       ┆ d58-4c6d-b ┆           ┆     ┆           ┆ 4         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ 52c2390c2 │
│       ┆ f4d-b690a2 ┆           ┆     ┆           ┆           ┆ 3.452451+ ┆ 3.452587+ ┆ bf28c3dfe │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ a03…      │
│ 76    ┆ b2c121df-4 ┆ user_76   ┆ 19  ┆ female    ┆ address_7 ┆ 2026-07-2 ┆ 2026-07-2 ┆ ff9e5f2d5 │
│       ┆ d3c-41e7-9 ┆           ┆     ┆           ┆ 5         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ b5f1a61b7 │
│       ┆ d36-e73103 ┆           ┆     ┆           ┆           ┆ 3.452453+ ┆ 3.452588+ ┆ 29a826f53 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 386…      │
│ 77    ┆ 4fd7e88e-7 ┆ user_77   ┆ 21  ┆ male      ┆ address_7 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 44e9490d9 │
│       ┆ 79b-44fb-a ┆           ┆     ┆           ┆ 6         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ 06e97e425 │
│       ┆ 410-abde6c ┆           ┆     ┆           ┆           ┆ 3.452454+ ┆ 3.452589+ ┆ ab4b3d997 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ e2f…      │
│ 78    ┆ 4d239862-9 ┆ user_78   ┆ 44  ┆ female    ┆ address_7 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 735e8e253 │
│       ┆ 6dd-4edb-b ┆           ┆     ┆           ┆ 7         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ 3a1328d58 │
│       ┆ 74e-bdaaa9 ┆           ┆     ┆           ┆           ┆ 3.452455+ ┆ 3.452591+ ┆ c6d52df1a │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ d20…      │
│ 79    ┆ 8c679dc1-1 ┆ user_79   ┆ 42  ┆ other     ┆ address_7 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 373c96b22 │
│       ┆ 1f4-422d-8 ┆           ┆     ┆           ┆ 8         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ c74c6e6f0 │
│       ┆ c7a-39023c ┆           ┆     ┆           ┆           ┆ 3.452456+ ┆ 3.452592+ ┆ 27d503efb │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 2db…      │
│ 80    ┆ 159da821-2 ┆ user_80   ┆ 33  ┆ female    ┆ address_7 ┆ 2026-07-2 ┆ 2026-07-2 ┆ c1fc42e78 │
│       ┆ b10-4384-a ┆           ┆     ┆           ┆ 9         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ cf275a033 │
│       ┆ 05c-5cda1a ┆           ┆     ┆           ┆           ┆ 3.452458+ ┆ 3.452593+ ┆ 01d859976 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ f96…      │
│ 81    ┆ e2f61000-e ┆ user_81   ┆ 35  ┆ other     ┆ address_8 ┆ 2026-07-2 ┆ 2026-07-2 ┆ aafa1947b │
│       ┆ 9b2-4e73-8 ┆           ┆     ┆           ┆ 0         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ cfffd6496 │
│       ┆ 279-18d75c ┆           ┆     ┆           ┆           ┆ 3.452459+ ┆ 3.452594+ ┆ 00223ff50 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 84a…      │
│ 82    ┆ e430f22a-e ┆ user_82   ┆ 58  ┆ female    ┆ address_8 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 326ac4323 │
│       ┆ d6a-4818-8 ┆           ┆     ┆           ┆ 1         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ 677f3d511 │
│       ┆ bb9-5f1fff ┆           ┆     ┆           ┆           ┆ 3.452460+ ┆ 3.452596+ ┆ dceefa96b │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 191…      │
│ 83    ┆ 5f5593cb-c ┆ user_83   ┆ 54  ┆ other     ┆ address_8 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 94df00cc7 │
│       ┆ 96b-410b-a ┆           ┆     ┆           ┆ 2         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ 1d2e5628e │
│       ┆ 080-9724c1 ┆           ┆     ┆           ┆           ┆ 3.452461+ ┆ 3.452597+ ┆ 2d2d34d74 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 655…      │
│ 84    ┆ 7a4f063d-2 ┆ user_84   ┆ 33  ┆ other     ┆ address_8 ┆ 2026-07-2 ┆ 2026-07-2 ┆ cdf29578f │
│       ┆ c06-45b4-8 ┆           ┆     ┆           ┆ 3         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ 2a26aee4f │
│       ┆ 05d-f45192 ┆           ┆     ┆           ┆           ┆ 3.452462+ ┆ 3.452598+ ┆ 27a9ca5d1 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 4b3…      │
│ 85    ┆ e1940b51-1 ┆ user_85   ┆ 37  ┆ male      ┆ address_8 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 335881558 │
│       ┆ 44e-43f9-9 ┆           ┆     ┆           ┆ 4         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ 9c12a3ff6 │
│       ┆ 35f-be171d ┆           ┆     ┆           ┆           ┆ 3.452464+ ┆ 3.452599+ ┆ df04448f7 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 1f4…      │
│ 86    ┆ 77415a98-f ┆ user_86   ┆ 33  ┆ female    ┆ address_8 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 36b2716d2 │
│       ┆ 5c4-47bf-9 ┆           ┆     ┆           ┆ 5         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ 3512c3d41 │
│       ┆ 6b3-6272bb ┆           ┆     ┆           ┆           ┆ 3.452465+ ┆ 3.452600+ ┆ 59bf030ed │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ f62…      │
│ 87    ┆ 8cfa4009-8 ┆ user_87   ┆ 39  ┆ male      ┆ address_8 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 430760a80 │
│       ┆ 21e-4943-8 ┆           ┆     ┆           ┆ 6         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ f319ff7a4 │
│       ┆ ff1-ed97f1 ┆           ┆     ┆           ┆           ┆ 3.452466+ ┆ 3.452602+ ┆ caff0c5ed │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ b07…      │
│ 88    ┆ 314a0eb1-7 ┆ user_88   ┆ 20  ┆ other     ┆ address_8 ┆ 2026-07-2 ┆ 2026-07-2 ┆ cb8c2e617 │
│       ┆ 070-4937-b ┆           ┆     ┆           ┆ 7         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ f16e300cf │
│       ┆ 2a9-456cc3 ┆           ┆     ┆           ┆           ┆ 3.452467+ ┆ 3.452603+ ┆ 665c647fa │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 30b…      │
│ 89    ┆ 9145f7e7-5 ┆ user_89   ┆ 32  ┆ other     ┆ address_8 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 1623053d0 │
│       ┆ a32-47ad-a ┆           ┆     ┆           ┆ 8         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ adbf3ca17 │
│       ┆ f6f-b991d5 ┆           ┆     ┆           ┆           ┆ 3.452468+ ┆ 3.452604+ ┆ d5e4aac28 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ a65…      │
│ 90    ┆ 63bb5ba9-4 ┆ user_90   ┆ 28  ┆ female    ┆ address_8 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 124cd5f13 │
│       ┆ dfd-4c8b-b ┆           ┆     ┆           ┆ 9         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ ba5ecd8b1 │
│       ┆ 3a1-ebbb4a ┆           ┆     ┆           ┆           ┆ 3.452470+ ┆ 3.452605+ ┆ cb09c0974 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ e38…      │
│ 91    ┆ 6ea69b67-a ┆ user_91   ┆ 51  ┆ other     ┆ address_9 ┆ 2026-07-2 ┆ 2026-07-2 ┆ c24b7eb73 │
│       ┆ 0bc-4adb-b ┆           ┆     ┆           ┆ 0         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ 2a4c08510 │
│       ┆ 9b1-f75f03 ┆           ┆     ┆           ┆           ┆ 3.452471+ ┆ 3.452606+ ┆ ffecf1c7f │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ e4d…      │
│ 100   ┆ cb7125e5-e ┆ user_100  ┆ 53  ┆ female    ┆ address_0 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 951f8eee1 │
│       ┆ 387-4293-a ┆           ┆     ┆           ┆           ┆ 8 15:07:3 ┆ 8 15:07:3 ┆ 9367c9285 │
│       ┆ ce9-5595f6 ┆           ┆     ┆           ┆           ┆ 3.465026+ ┆ 3.465043+ ┆ 74fb01ca1 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 86e…      │
│ 101   ┆ e1156d07-0 ┆ user_101  ┆ 35  ┆ female    ┆ address_1 ┆ 2026-07-2 ┆ 2026-07-2 ┆ dd50b8728 │
│       ┆ 2d2-4bb1-8 ┆           ┆     ┆           ┆           ┆ 8 15:07:3 ┆ 8 15:07:3 ┆ 34009da40 │
│       ┆ 44c-176835 ┆           ┆     ┆           ┆           ┆ 3.465031+ ┆ 3.465044+ ┆ 0bc4f7271 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 535…      │
│ 102   ┆ fc367caa-d ┆ user_102  ┆ 46  ┆ female    ┆ address_2 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 8d0f0f411 │
│       ┆ 82a-4b2a-b ┆           ┆     ┆           ┆           ┆ 8 15:07:3 ┆ 8 15:07:3 ┆ 56d327e2f │
│       ┆ 352-29f85d ┆           ┆     ┆           ┆           ┆ 3.465032+ ┆ 3.465044+ ┆ 28102db0f │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 7ff…      │
│ 103   ┆ 3e4407a3-3 ┆ user_103  ┆ 25  ┆ female    ┆ address_3 ┆ 2026-07-2 ┆ 2026-07-2 ┆ b63e2e2aa │
│       ┆ d40-46e1-8 ┆           ┆     ┆           ┆           ┆ 8 15:07:3 ┆ 8 15:07:3 ┆ 7dbc6b726 │
│       ┆ 815-cc7871 ┆           ┆     ┆           ┆           ┆ 3.465032+ ┆ 3.465045+ ┆ 7bc98cd58 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 8f5…      │
│ 104   ┆ d93156c9-e ┆ user_104  ┆ 29  ┆ male      ┆ address_4 ┆ 2026-07-2 ┆ 2026-07-2 ┆ b7be32699 │
│       ┆ 798-456e-a ┆           ┆     ┆           ┆           ┆ 8 15:07:3 ┆ 8 15:07:3 ┆ ce80dded2 │
│       ┆ 768-c51fa4 ┆           ┆     ┆           ┆           ┆ 3.465033+ ┆ 3.465045+ ┆ d5c70ae9b │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 9eb…      │
│ 105   ┆ 05aef341-7 ┆ user_105  ┆ 49  ┆ female    ┆ address_5 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 97287f26b │
│       ┆ 422-4726-8 ┆           ┆     ┆           ┆           ┆ 8 15:07:3 ┆ 8 15:07:3 ┆ 0c86451a2 │
│       ┆ 49d-68e79a ┆           ┆     ┆           ┆           ┆ 3.465034+ ┆ 3.465046+ ┆ 3333f1d14 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 057…      │
│ 106   ┆ 1a1b4075-d ┆ user_106  ┆ 47  ┆ female    ┆ address_6 ┆ 2026-07-2 ┆ 2026-07-2 ┆ cb6e15ecc │
│       ┆ 8b4-4ce4-a ┆           ┆     ┆           ┆           ┆ 8 15:07:3 ┆ 8 15:07:3 ┆ 7e3cdb0f1 │
│       ┆ ac4-2b4599 ┆           ┆     ┆           ┆           ┆ 3.465034+ ┆ 3.465047+ ┆ 36e8f5ad6 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ bf1…      │
│ 107   ┆ 5150c734-d ┆ user_107  ┆ 40  ┆ male      ┆ address_7 ┆ 2026-07-2 ┆ 2026-07-2 ┆ d36f6d059 │
│       ┆ cc1-4543-8 ┆           ┆     ┆           ┆           ┆ 8 15:07:3 ┆ 8 15:07:3 ┆ d20f3b905 │
│       ┆ 576-879dbe ┆           ┆     ┆           ┆           ┆ 3.465040+ ┆ 3.465047+ ┆ 68cce90bb │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 435…      │
│ 108   ┆ 2f8d5e6e-4 ┆ user_108  ┆ 52  ┆ female    ┆ address_8 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 5168e5f44 │
│       ┆ dee-458c-a ┆           ┆     ┆           ┆           ┆ 8 15:07:3 ┆ 8 15:07:3 ┆ be24ee61e │
│       ┆ acc-042de0 ┆           ┆     ┆           ┆           ┆ 3.465040+ ┆ 3.465048+ ┆ e1c7249e4 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 280…      │
│ 109   ┆ 9e8030ec-5 ┆ user_109  ┆ 56  ┆ female    ┆ address_9 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 2b9bf951c │
│       ┆ 45c-494b-8 ┆           ┆     ┆           ┆           ┆ 8 15:07:3 ┆ 8 15:07:3 ┆ e1ed100f4 │
│       ┆ f3c-35458d ┆           ┆     ┆           ┆           ┆ 3.465041+ ┆ 3.465049+ ┆ 812de168e │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ be8…      │
│ 1     ┆ b8bbe9fa-d ┆ user_1_ch ┆ 59  ┆ female_ch ┆ address_0 ┆ 2026-07-2 ┆ 2026-07-2 ┆ e74fe3a67 │
│       ┆ 95e-43f4-8 ┆ ange_all  ┆     ┆ ange_all  ┆ _change_a ┆ 6 15:07:3 ┆ 8 15:07:3 ┆ c966f8793 │
│       ┆ c12-178437 ┆           ┆     ┆           ┆ ll        ┆ 3.452340+ ┆ 3.452484+ ┆ d87e9e26f │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ da4…      │
│ 2     ┆ 9311ec4b-3 ┆ user_2_ch ┆ 27  ┆ female_ch ┆ address_1 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 0c7275bd9 │
│       ┆ 168-40ee-8 ┆ ange_all  ┆     ┆ ange_all  ┆ _change_a ┆ 6 15:07:3 ┆ 8 15:07:3 ┆ 3da553699 │
│       ┆ 6c3-0e2281 ┆           ┆     ┆           ┆ ll        ┆ 3.452355+ ┆ 3.452486+ ┆ 9c087dfc4 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 1a9…      │
│ 3     ┆ 789473f0-9 ┆ user_3_ch ┆ 39  ┆ male_chan ┆ address_2 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 0052f14f5 │
│       ┆ 722-4006-b ┆ ange_all  ┆     ┆ ge_all    ┆ _change_a ┆ 6 15:07:3 ┆ 8 15:07:3 ┆ 8f991edbd │
│       ┆ 709-c28ac6 ┆           ┆     ┆           ┆ ll        ┆ 3.452357+ ┆ 3.452487+ ┆ a73033571 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 34e…      │
│ 4     ┆ 4830150b-4 ┆ user_4_ch ┆ 23  ┆ female_ch ┆ address_3 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 32576253d │
│       ┆ 8c3-4117-9 ┆ ange_all  ┆     ┆ ange_all  ┆ _change_a ┆ 6 15:07:3 ┆ 8 15:07:3 ┆ 1b5f5eb30 │
│       ┆ 37e-f619a6 ┆           ┆     ┆           ┆ ll        ┆ 3.452358+ ┆ 3.452489+ ┆ d09c097c2 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 1fa…      │
│ 5     ┆ 16a9cdbb-6 ┆ user_5_ch ┆ 49  ┆ other_cha ┆ address_4 ┆ 2026-07-2 ┆ 2026-07-2 ┆ f49ed879e │
│       ┆ cae-4a76-a ┆ ange_all  ┆     ┆ nge_all   ┆ _change_a ┆ 6 15:07:3 ┆ 8 15:07:3 ┆ 1cda8a637 │
│       ┆ 57a-0aa10f ┆           ┆     ┆           ┆ ll        ┆ 3.452359+ ┆ 3.452490+ ┆ 1ff6894c1 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 6db…      │
│ 6     ┆ c17a86e9-2 ┆ user_6_ch ┆ 20  ┆ other_cha ┆ address_5 ┆ 2026-07-2 ┆ 2026-07-2 ┆ fbc8a1292 │
│       ┆ 4a4-43ef-a ┆ ange_all  ┆     ┆ nge_all   ┆ _change_a ┆ 6 15:07:3 ┆ 8 15:07:3 ┆ fed1932ba │
│       ┆ 717-01bbe3 ┆           ┆     ┆           ┆ ll        ┆ 3.452361+ ┆ 3.452491+ ┆ 1185663a2 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 8b9…      │
│ 7     ┆ 355f5e35-6 ┆ user_7_ch ┆ 41  ┆ other_cha ┆ address_6 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 32ca64716 │
│       ┆ b25-4f1f-a ┆ ange_all  ┆     ┆ nge_all   ┆ _change_a ┆ 6 15:07:3 ┆ 8 15:07:3 ┆ 4f254ca9a │
│       ┆ f25-28e4b2 ┆           ┆     ┆           ┆ ll        ┆ 3.452362+ ┆ 3.452492+ ┆ 03dccc361 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ ca3…      │
│ 8     ┆ 1c71d525-4 ┆ user_8_ch ┆ 42  ┆ female_ch ┆ address_7 ┆ 2026-07-2 ┆ 2026-07-2 ┆ bd9c00d03 │
│       ┆ e59-4370-8 ┆ ange_all  ┆     ┆ ange_all  ┆ _change_a ┆ 6 15:07:3 ┆ 8 15:07:3 ┆ 057303339 │
│       ┆ 1e0-244b92 ┆           ┆     ┆           ┆ ll        ┆ 3.452365+ ┆ 3.452494+ ┆ cd9247700 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 5b7…      │
│ 9     ┆ f72d8493-8 ┆ user_9_ch ┆ 37  ┆ female_ch ┆ address_8 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 5bf7f3358 │
│       ┆ 453-46fc-a ┆ ange_all  ┆     ┆ ange_all  ┆ _change_a ┆ 6 15:07:3 ┆ 8 15:07:3 ┆ 73f5c2aa6 │
│       ┆ 7fa-34f289 ┆           ┆     ┆           ┆ ll        ┆ 3.452367+ ┆ 3.452496+ ┆ 8d0c43efd │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 893…      │
│ 10    ┆ 6617eeb0-6 ┆ user_10_c ┆ 20  ┆ male_chan ┆ address_9 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 418aaa7d3 │
│       ┆ ba6-48f1-8 ┆ hange_all ┆     ┆ ge_all    ┆ _change_a ┆ 6 15:07:3 ┆ 8 15:07:3 ┆ 8e3bac43b │
│       ┆ b30-18ea1b ┆           ┆     ┆           ┆ ll        ┆ 3.452368+ ┆ 3.452497+ ┆ ff290c8f9 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 0a5…      │
│ 11    ┆ 96da0bec-d ┆ user_11_c ┆ 56  ┆ male      ┆ address_1 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 879231985 │
│       ┆ f32-4027-9 ┆ hange_nam ┆     ┆           ┆ 0         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ 1c6f911b4 │
│       ┆ 65d-8aafba ┆ e         ┆     ┆           ┆           ┆ 3.452370+ ┆ 3.452498+ ┆ e4bf63534 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 283…      │
│ 12    ┆ 107c0f9d-c ┆ user_12_c ┆ 28  ┆ male      ┆ address_1 ┆ 2026-07-2 ┆ 2026-07-2 ┆ f53e49874 │
│       ┆ ea0-4dc6-9 ┆ hange_nam ┆     ┆           ┆ 1         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ 23b504f90 │
│       ┆ 194-d136e1 ┆ e         ┆     ┆           ┆           ┆ 3.452371+ ┆ 3.452500+ ┆ 6db66fef1 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 64c…      │
│ 13    ┆ 34c2bbbe-1 ┆ user_13_c ┆ 44  ┆ female    ┆ address_1 ┆ 2026-07-2 ┆ 2026-07-2 ┆ faa3ebdad │
│       ┆ a06-4dfb-b ┆ hange_nam ┆     ┆           ┆ 2         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ 9cb7796ec │
│       ┆ 849-e8c67d ┆ e         ┆     ┆           ┆           ┆ 3.452372+ ┆ 3.452501+ ┆ e0eff95bf │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 093…      │
│ 14    ┆ aba37a8b-3 ┆ user_14_c ┆ 30  ┆ female    ┆ address_1 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 06ab29f06 │
│       ┆ 2a0-4580-a ┆ hange_nam ┆     ┆           ┆ 3         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ f66b95806 │
│       ┆ f12-44e53c ┆ e         ┆     ┆           ┆           ┆ 3.452374+ ┆ 3.452502+ ┆ eeb42f8d5 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 42e…      │
│ 15    ┆ ef4eb4e0-2 ┆ user_15_c ┆ 48  ┆ other     ┆ address_1 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 39274f474 │
│       ┆ 2ca-49fc-9 ┆ hange_nam ┆     ┆           ┆ 4         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ 10ee6cef5 │
│       ┆ aa1-f72792 ┆ e         ┆     ┆           ┆           ┆ 3.452375+ ┆ 3.452503+ ┆ 74c36805e │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 3d5…      │
│ 16    ┆ 397b3358-0 ┆ user_16_c ┆ 57  ┆ other     ┆ address_1 ┆ 2026-07-2 ┆ 2026-07-2 ┆ f1b7da941 │
│       ┆ cbf-43ba-b ┆ hange_nam ┆     ┆           ┆ 5         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ e96312677 │
│       ┆ 98e-f13483 ┆ e         ┆     ┆           ┆           ┆ 3.452376+ ┆ 3.452504+ ┆ f9a0f6ae2 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 6c4…      │
│ 17    ┆ 7c6dac5e-9 ┆ user_17_c ┆ 56  ┆ male      ┆ address_1 ┆ 2026-07-2 ┆ 2026-07-2 ┆ f07cd5a32 │
│       ┆ 879-4c1c-b ┆ hange_nam ┆     ┆           ┆ 6         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ 164978924 │
│       ┆ 217-6d6b23 ┆ e         ┆     ┆           ┆           ┆ 3.452377+ ┆ 3.452506+ ┆ 85338b720 │
│       ┆ …          ┆           ┆     ┆           ┆           ┆ 07:…      ┆ 07:…      ┆ 3ba…      │
│ 18    ┆ 0e6a0874-b ┆ user_18_c ┆ 26  ┆ male      ┆ address_1 ┆ 2026-07-2 ┆ 2026-07-2 ┆ 34f0bf526 │
│       ┆ 120-4119-b ┆ hange_nam ┆     ┆           ┆ 7         ┆ 7 15:07:3 ┆ 7 15:07:3 ┆ 4025f3697 │
│       ┆ 4ca-beccdb ┆ e         ┆     ┆           ┆           ┆ 3.452379+ ┆ 3.452507+ ┆ a2628f75a │

In [ ]:
df_current_hashed.drop("hashed_row").sink_parquet("/home/user/workspace3/data/brozen/data.parquet")

if updated at and created at not change, but any column change inside it? how to track, if cdc just check based on updated at? missing many case: 

df_update_all, -> can track

df_update_name, -> not track

df_update_age, -> not track

df_update_gender, -> not track

df_update_address, -> not track

df_update_created_at, -> not track

df_update_updated_at, -> track

df_new, -> track